config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :transactions
  devise_for :users
  get 'login/index'

    authenticated :user do
      root to: 'transactions#index', as: "authenticated_root"
    end

    root to: 'login#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :transactions, :dependent => :delete_all
  belongs_to :user
  validates :user, presence: true
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  validates_presence_of :description, :user, :amount, :category
  enum ttype: [ :cost, :income ]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :categories, dependent: :destroy
  has_many :transactions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find params[:id]
    unless current_user == @category.user
      redirect_to(@category, notice: "Access denied.") and return
    end
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    unless current_user == @category.user
      redirect_to(categories_url, notice: "You can't destroy this category because you didn't create it.") and return
    else
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.where(user_id: current_user)
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])
    unless current_user == @transaction.user
      redirect_to(transactions_url, notice: "You can't view this transaction because you didn't create it.") and return
    end
  end

  # GET /transactions/new
  def new
    @transaction = current_user.transactions.build
    @ttypes = Transaction.ttypes
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find params[:id]
    @ttypes = Transaction.ttypes
    unless current_user == @transaction.user
      redirect_to(transactions_url, notice: "You can't edit this transaction because you didn't create it.") and return
    end
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = current_user.transactions.build(transaction_params)
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])
    @ttypes = Transaction.ttypes
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    unless current_user == @transaction.user
      redirect_to(transactions_url, notice: "You can't edit this transaction because you didn't create it.") and return
    else
      @transaction.destroy
      respond_to do |format|
        format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:amount, :ttype, :category_id, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_form.html.haml
#category_form
  = simple_form_for(@category, html: {class: 'form-horizontal'}) do |f|
    = f.input :name, label: "Category", required: true, input_html: {class: "form-control"}
    %br/
    = f.button :submit, class: "button"
    %br/

app/views/categories/create.js.erb
var new_category = $("<%= escape_javascript(render(:partial => @category))%>").hide();
$('#categories').prepend(new_category);
$("#new_category").bind("ajax:beforeSend", function(event,xhr,status){
  $('#category_content').val('');
}
$('#category_<%= @category.id %>').fadeIn('fast');
$('#new_category')[0].reset();

app/views/categories/edit.html.haml
%h1 Editing Category

= render 'form'
%br/
= link_to "View Category", @category, class: "button"
= link_to "All Categories", categories_path, class: "button"

app/views/categories/index.html.erb
<div id ="index_categories">
  <h1>Listing Categories</h1>
  <br>
  <br>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Category', new_category_path, class: "button" %>
</div>

app/views/categories/new.html.haml
#new_category
  %h1 New Category

  = render 'form'
  %br/
  = link_to "Back to Categories", categories_path, class: "button"

app/views/categories/show.html.haml
#category
  #cat_index_header
    %h2 Transactions in category:
    %h1= @category.name
  #cat_index_body
    %br/
    %br/
    %table
      %thead
        %tr
          %th Transaction Description
          %th Transaction Amount
          %th Transaction Type
        %tbody
        - @category.transactions.each do |transaction|
          %tr
            %td= link_to transaction.description, transaction
            %td= transaction.amount
            %td= transaction.ttype
            %td= link_to 'Edit Transaction', edit_transaction_path(transaction)
            %td= link_to 'Delete Transaction', transaction, method: :delete, data: { confirm: 'By deleting this category, you will delete all associated transactions. If this was not your intention, click `Cancel` and choose to edit the category instead.' }


  %br/
  %br/
  = link_to 'Edit', edit_category_path(@category), class: "button"
  = link_to 'Categories', categories_path, class: "button"
  = link_to 'Transactions', transactions_path, class: "button"
  = link_to 'Create Transaction', new_transaction_path, class: "button"

app/views/layouts/application.html.haml
!!!
%html
  %head>
    %title My Wallet
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %nav
        .header_container
          .navbar-header
            = link_to "My Wallet", transactions_path, class: "navbar-brand"
          .nav.navbar-nav.navbar-right
            - if user_signed_in?
              = link_to "New Transaction", new_transaction_path, class: "navbar-brand"
              = link_to "New Category", new_category_path, class: "navbar-brand"
              = link_to "All Transactions", transactions_path, class: "navbar-brand"
              = link_to "All Categories", categories_path, class: "navbar-brand"
              = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-brand"
            - else
              = link_to "Log In", new_user_session_path, class: "navbar-brand"
    .container
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/login/index.html.haml
#banner
  .banner_content
    %h2 My Wallet
    %h3 Helping you to track your spending.
    %br/
    %link_to= link_to "Sign Up", new_user_registration_path, class: "button"
    %link_to= link_to "Log In", new_user_session_path, class: "button"

app/views/transactions/_form.html.haml
#transaction_form
  = simple_form_for(@transaction, html: {class: 'form-horizontal'}) do |f|
    = f.input :description, label: "Description", required: true, input_html: {class: "form-control"}
    = f.input :amount, label: "Amount", required: true, input_html: {class: "form-control"}
    %br/
    = f.select :ttype, options_for_select(@ttypes.collect { |s| [s[0].humanize, s[0]] },
    selected:@transaction.ttype), label: "Cost or Income: ", required: true, input_html: {class: "form-control" }
    %br/
    %br/
    %p * Category
    = f.collection_select(:category_id, Category.all, :id, :name, { :prompt => false,
      :selected => @transaction.category_id, :include_blank => false, :required => true }, { class: 'form-control' })
    %br/
    = f.button :submit, class: "button"
    %br/
    %br/
  %h3 If you don't see your desired category in the drop-down menu, please enter a new category label below:
  %br/
  #comments
    = simple_form_for([@category, Category.new], remote: false, html: {class: 'form-horizontal'}) do |f|
      = f.input :name, label: "New Category", required: true, input_html: {class: "form-control"}
      %br/
      = f.button :submit, "Save", class: "button"
    %br/
    %br/

app/views/transactions/edit.html.haml
#transaction_edit
  %h1 Editing Transaction

  = render 'form'

  %link_to= link_to 'Show', @transaction, class: "button"
  %link_to= link_to 'Back', transactions_path, class: "button"

app/views/transactions/index.html.haml
!!!
%html
  %head
  .wrapper_with_padding
    - [:notice]
    #div.centre
      - if (current_user.transactions.count > 0)
        %h1= "Total Income: $#{current_user.transactions.where(:ttype => 1).sum(:amount)}"
        %br/
        %br/
        %h1= "Total Spent: $#{current_user.transactions.where(:ttype => 0).sum(:amount)}"
        %br/
        %br/
        %br/
    - unless @transactions.blank?
      %table
        %thead
          %tr
            %th Description
            %th Category
            %th Amount
            %th Transaction type
        %tbody
        - @transactions.each do |transaction|
          %tr
            %td= link_to transaction.description, transaction
            %td= link_to transaction.category.name, transaction.category
            %td= transaction.amount
            %td= transaction.ttype
            %td= link_to 'Edit', edit_transaction_path(transaction)
            %td= link_to 'Delete', transaction, method: :delete, data: { confirm: 'Are you sure?' }
      %br/
    - else
      %h3 You have not entered any transactions yet.
      %br/
    %br/
    %br/
    %br/
    %link_to= link_to "New Transaction", new_transaction_path, class: "button"

app/views/transactions/new.html.haml
#new_transaction
  %h3 New Transaction

  = render 'form'

  %link_to= link_to 'Back', transactions_path, class: "button"

app/views/transactions/show.html.erb
<div id="transaction_show">
  <p>
    <strong>Description:</strong>
    <%= @transaction.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= @transaction.amount %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= @transaction.ttype %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= link_to @transaction.category.name, @transaction.category %>
  </p>
  <br/>
  <%= link_to 'Edit', edit_transaction_path(@transaction), class: "button" %>
  <%= link_to 'Delete', @transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></td>
  <%= link_to 'Transactions', transactions_path, class: "button" %>
  <%= link_to 'Categories', categories_path, class: "button" %>
</div>